server {
    listen 80;
    server_name _;
    root /var/www/laravel-12-architecture/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass laravel-12-architecture:8000; # PHP-FPM'ga ulanish
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    access_log /var/log/nginx/laravel-12-architecture_access_get.log;
    error_log /var/log/nginx/laravel-12-architecture_error_get.log;

    location ~ /\.ht {
        deny all;
    }
}
